Wip readme update mb
learn-co-curriculum/navigating-curriculum-on-learn-ide pull request #3
Opened 2018-05-29 16:11 UTC by sgharms

2018-05-29 17:21 UTC, sgharms reviewed
@maxwellbenton i have a few tiny adjustments to this branch. Once done could you please update the spreadsheet and assign Kellye and let her know to review this as well.

2018-05-29 17:21 UTC, sgharms commented on README.md
>  ![Click for Navigation dropdown](https://curriculum-content.s3.amazonaws.com/intro-to-learn/HowToNavigateCurriculum.png)
@maxwellbenton I think these screen shots are out of date. Note missing "lab" flask icon, missing readme icon, drop down doesn't seem to function that way anymore.

2018-05-29 17:21 UTC, sgharms commented on README.md
>  ![View Navigation dropdown](https://curriculum-content.s3.amazonaws.com/intro-to-learn/ExpandedNav.png)
Also: probably need some text atop this one to contextualize what the screenshot is. Two shots stacked one on top of each other is a bit weird looking.

2018-05-29 17:21 UTC, sgharms commented on README.md
> +Later lessons build off the earlier ones, so you must complete a lesson before
This isn't strictly true. Can we **strongly advise** instead?

2018-05-29 17:21 UTC, sgharms commented on README.md
> +Labs are lessons with a coding challenge you must complete. A lab will require
Could we include screenshots of

(flask icon) derp lab

(readme icon) derp README

so that students know what they look like looking from the curriculum drop down?

2018-05-29 17:21 UTC, sgharms commented on README.md
> +right. The "Next Lesson" button will light up, allowing you to proceed.
Can we put captions between the before / after state on these.

2018-05-31 17:47 UTC, maxwellbenton commented
@sgharms got it, thanks! I've made the changes based on your feedback - updated screenshots, added captions for clarity, added in readme/lab icons and a brief explanation, and corrected information

2018-05-31 18:03 UTC, drakeltheryuujin requested changes
Only 1 piece of suggested feedback, other than that, good to go imo!

2018-05-31 18:03 UTC, drakeltheryuujin commented on README.md
> -right. The "Next Lesson" button will light up, allowing you to proceed.
My only feedback I see is that these feels like `The video augments the content; it does not replace it.` should have **bold** emphasis. I think this is something that should stick in the readers' mind.

2018-05-31 18:12 UTC, merged